engines: 
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
      enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:

ratings:
  paths:
    - "**.css"
    - "**.js"
exclude_paths:
- tests/
- node_modules/
