engines: 
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
      enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  nodesecurity:
    enabled: true

  ratings:
    paths:
      - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- node_modules/

