engines: 
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
      enabled: true
  csslint:
    enabled: true

ratings:
  paths:
    - "**.css"
    - "**.js"
exclude_paths:
- tests/
- node_modules/
